save_folder_name = "backpack_dog"

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
prompt = "[P] backpack, on a chair, best quality"
neg_prompt = ""
batch_size = 4
num_batches = 1

[[loras]]
file_path = "zhangandi001/SDXL_Dreambooth_LoRAs"
file_name = "backpack_dog.safetensors"
adapter_name = "backpack_dog"
adapter_weight = 1.0