save_folder_name = "dog6"

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
prompt = "[V] dog and balloons, best quality"
neg_prompt = ""
batch_size = 4
num_batches = 1

[[loras]]
file_path = "zhangandi001/SDXL_Dreambooth_LoRAs"
file_name = "dog6.safetensors"
adapter_name = "dog6"
adapter_weight = 1.0
