save_folder_name = "duck_toy"

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
prompt = "[B] duck, swimming, best quality"
neg_prompt = ""
batch_size = 4
num_batches = 1

[[loras]]
file_path = "zhangandi001/SDXL_Dreambooth_LoRAs"
file_name = "duck_toy.safetensors"
adapter_name = "duck_toy"
adapter_weight = 1.0