save_folder_name = "keqing"

pipe_id = "cagliostrolab/animagine-xl-3.1"
prompt = "keqing (genshin impact) and balloons,portrait,guanfu, purple hair , twintails, hair ornament ,bare shoulders ,cone hair bun ,dress ,hair bun ,detached sleeves ,black pantyhose, guofeng, chinese style, best quality, masterpiece"
neg_prompt = "NSFW, hands, (worst quality, low quality:1.4),(depth of field, bokeh, blurry, film grain, chromatic aberration, lens flare:1.4),(sketch, Brush Touch:1.2),(motion lines, motion blur, emphasis lines:1.2),monochrome,zombie,(2girls:1.3),(interlocked fingers:1.35),badhandv4,(text,watermark:1.3),bad-artist-anime,nsfw,bad-hands-5,"
batch_size = 4
num_batches = 1

[[loras]]
file_path = "anonymousrepos/SDXL_LoRA_Models"
file_name = "community/keqing.safetensors"
adapter_name = "keqing"
adapter_weight = 1.0
