save_folder_name = "dog6_cloud"

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
prompt = "cloud that looks like, [V] dog, best quality"
neg_prompt = ""
batch_size = 4
num_batches = 1

[[loras]]
file_path = "joachimsallstrom/aether-cloud-lora-for-sdxl"
file_name = "Aether_Cloud_v1.safetensors"
adapter_name = "cloud"
dropout_rate = 0.5
adapter_weight = 1.0

[[loras]]
file_path = "zhangandi001/SDXL_Dreambooth_LoRAs"
file_name = "dog6.safetensors"
adapter_name = "dog6"
dropout_rate = 0.5
adapter_weight = 1.0
