save_folder_name = "kimoju_cloud"

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
prompt = "cloud that looks like, kimo_ju, best quality, masterpiece"
neg_prompt = ""
batch_size = 4
num_batches = 1

[[loras]]
file_path = "joachimsallstrom/aether-cloud-lora-for-sdxl"
file_name = "Aether_Cloud_v1.safetensors"
adapter_name = "cloud"
dropout_rate = 0.5
adapter_weight = 1.0

[[loras]]
file_path = "zhangandi001/SDXL_Kimoju_LoRA"
file_name = "kimoju.safetensors"
adapter_name = "kimoju"
dropout_rate = 0.5
adapter_weight = 1.0